### ISSUE TITLE
Зачем в заказе хранить логин-пароль клиента?

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task-2-web-mvc#1]
https://github.com/Vi3arD/spring-course-task-2-web-mvc/blob/692a4d66e006d6a64eb57bade844e14e0b0922d5/src/main/java/org/example/repository/OrderRepository.java#L20-L21

**Comment by Vi3arD** [comment]
@coursar тогда получается что эти два поля нужно хранить в отдельной таблице скажем User а в Order хранить ссылки на данного юзера?

**Comment by coursar** [comment]
Да

**Comment by Vi3arD** [comment]
@coursar закрыл все issues, проверьте пожалуйста
