### ISSUE TITLE
Добавить лимит, offset и order by

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task-2-web-mvc#2]
https://github.com/Vi3arD/spring-course-task-2-web-mvc/blob/692a4d66e006d6a64eb57bade844e14e0b0922d5/src/main/java/org/example/repository/OrderRepository.java#L35

**Comment by Vi3arD** [comment]
@coursar данный метод не используется в конечном контролере, как Вы уже заметили в issue #15. Есть ли тогда смысл добавлять limit и offset?

**Comment by coursar** [comment]
Тогда его стоит удалить
