### ISSUE TITLE
Тесты лучше писать хотя бы в таком виде, иначе как вы проверите, что всё работает? Заново руками будете запускать?

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task-2-web-mvc#20]
https://github.com/Vi3arD/spring-course-task-2-web-mvc/blob/611fcb29129ade2c148f3c5182d882bb657c3b5d/src/test/resources/requests.http#L1-L87

**Comment by Vi3arD** [comment]
@coursar у меня intellij idea community edition и отправлять из нее http запросы, как Вы показываете на лециях я не могу, поэтому для тестов я использую postman и соотвественно поскольку я не пользуюсь данным методом тестов, я и не менял этот файлик

**Comment by coursar** [comment]
Прикладывайте Postman'увскую коллекцию, ничего страшного.

При необходимости, могу вам выдать купон на несколько месяцев для IDEA Ultimate.
