### ISSUE TITLE
Насколько логично в контексте задачи давать возможность обновлять всю запись целиком?

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task-2-web-mvc#3]
https://github.com/Vi3arD/spring-course-task-2-web-mvc/blob/692a4d66e006d6a64eb57bade844e14e0b0922d5/src/main/java/org/example/repository/OrderRepository.java#L70

**Comment by Vi3arD** [comment]
согласен, в контексте задачи, давать конечному пользователю обновлять сущность нет смысла, поправлю
