### ISSUE TITLE
Желательно, чтобы методы сервиса маппились на бизнес-логику. Сейчас он больше похож на CRUD-сервис

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task-2-web-mvc#5]
https://github.com/Vi3arD/spring-course-task-2-web-mvc/blob/692a4d66e006d6a64eb57bade844e14e0b0922d5/src/main/java/org/example/service/OrderService.java#L17-L35

**Comment by Vi3arD** [comment]
@coursar вы имеете в виду просто просто их переименовать в соотвествии с бизнес задачами в которых они используются?

**Comment by coursar** [comment]
Да
