### ISSUE TITLE
url'ы и параметры не совпадают с оригинальным сервисом

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task-2-web-mvc#7]
https://github.com/Vi3arD/spring-course-task-2-web-mvc/blob/692a4d66e006d6a64eb57bade844e14e0b0922d5/src/main/java/org/example/controller/OrderController.java#L10

**Comment by Vi3arD** [comment]
@coursar в оригинальном сервисы идет примерно такой мапинг "/rest/reverse.do" то есть каждый метод имеет свой глагол, делать по аналогии с ним?

**Comment by coursar** [comment]
Да
